### ISSUE TITLE
Create QR Code Aggregator

### ISSUE THREAD

**Issue by bqrichards** [DisruptiveInnovation6317/CSP-Android#1]
Add a `Fragment` to the navigation drawer that serves as both a `ListView` for viewing data that has been scanned, as well as a QR code scanner.

**Comment by deadman96385** [comment]
Saw your app while looking at others
https://github.com/kenglxn/QRGen is a great QR Code generator library 
https://github.com/dm77/barcodescanner is a good QR/Barcode scanner library.
http://opencsv.sourceforge.net/ is the easiest way to write/read CSV files

**Comment by deadman96385** [comment]
If you want some examples of how to use those libraries you can take a look at our WIP scouting app https://github.com/databits3883/Android-FRC-Scouting

**Comment by bqrichards** [comment]
Thank you @deadman96385! We used the https://github.com/dm77/barcodescanner library that you recommended and it works fantastic.

**Comment by bqrichards** [comment]
This issue has been closed by release v1.0
